import Link from "next/link";

type Props = {
  params: {
    id: string;
  };
};

export const generateMetadata = ({ params }: Props) => {
  return {
    title: "안녕하세요. About Page 입니다",
    description: "Generated by create next app",
  };
};

const AboutPage = () => {
  return (
    <>
      <Link href={"/about2"}>about 2로 가!</Link>
    </>
  );
};

export default AboutPage;
